from app.routes.auth import auth_bp
from app.routes.users import users_bp
from app.routes.wallets import wallets_bp
from app.routes.transactions import transactions_bp
from app.routes.bills import bills_bp
from app.routes.cards import cards_bp
from app.routes.documents import documents_bp
from app.routes.assistant import assistant_bp
from app.routes.orderbook import orderbook_bp
from app.routes.goals import goals_bp
from app.routes.dashboard import dashboard_bp
from app.routes.insights import insights_bp
from app.routes.portfolio import portfolio_bp
